---
- name: Ensure gpg is installed
  apt:
    name: gpg
    state: present

- name: Ensure acl is installed
  apt:
    name: acl
    state: present

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present

- name: Ensure psycopg2 is installed
  pip:
    name: psycopg2-binary
    state: present